name: DemoQA Selenium ubuntu-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '0 6,8,20,22 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name:  Install Google Chrome # Using shell script to install Google Chrome
        run:   |
                chmod +x ./scripts/InstallChrome.sh
                            ./scripts/InstallChrome.sh 

      - name: Verificar existencia del archivo .bat
        run: |
          # Verificar si el archivo .bat existe
          if [ -f archivo.bat ]; then
            echo "El archivo archivo.bat existe"
            chmod +x ./scripts/kill_chromedriver.bat  # Otorgar permisos de ejecución
          else
            echo "El archivo archivo.bat no existe"
            exit 1
          fi

      - name: Ejecutar archivo .bat
        run: |
          ./scripts/kill_chromedriver.bat


      
      - name: Maven Verify
        run: mvn -B clean test

      - name: Deploy
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./ExtentReports
